### ISSUE TITLE
Needs a 64x64 and 128x128 icon

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.Calculator#1]
In order to show up on the [apps page](https://beta.flathub.org/apps) this needs at least a 64x64 icon. These appear to be the only icons missing in the source, there's 256x256! SVG! Everything! https://git.gnome.org/browse/gnome-calculator/tree/data/icons

**Comment by evfool** [comment]
It turned out it needs a rename-icon directive, and that generates the icons for the application in the given size. I think I will go with this fix, as e.g gedit doesn't distribute 64x64 and 128x128 icon, but still has an icon on flathab, probably due to the rename-icon directive.

**Comment by evfool** [comment]
Reopening, due to the fact that the icon rename did happen on master, but is not on the gnome-3-26 branch, so flatpak build fails with this change. Will mark it as fixed after porting the icon rename change to gnome-3-26 branch if possible, if not possible will figure out another way.

**Comment by nedrichards** [comment]
@evfool you could just wait until 3.28 as well, right? Although obviously that would be less than ideal.

**Comment by evfool** [comment]
@nedrichards of course, waiting until 3.28 is also possible. The commit adding the icons in-repo seems backportable, but I will have to figure out the details on where does flathub take the source from, is it a branch, or is it a release tarball. If I can't figure out, I'll probably just choose the easy way of waiting for the next release, and updating the manifest afterwards.

**Comment by nedrichards** [comment]
@evfool it's the release tarballs https://github.com/flathub/org.gnome.Calculator/blob/master/org.gnome.Calculator.json#L57

**Comment by nedrichards** [comment]
We could of course take a downstream patch as well, but an upstream release would be preferable, it'd fix the issue for everybody!

**Comment by nedrichards** [comment]
Fixed in the short term by #2
