### ISSUE TITLE
Excessive permissions

### ISSUE THREAD

**Issue by arteeh** [flathub/org.gnome.Calculator#18]
Calculator doesn't seem to need the following permissions, so they can be removed:
"--share=ipc"
"--share=network"

**Comment by evfool** [comment]
As getting currency conversion rates requires internet connection, I think that is the reason for network share. I am not sure about IPC though, I need to check.

**Comment by hfiguiere** [comment]
> As getting currency conversion rates requires internet connection, I think that is the reason for network share. I am not sure about IPC though, I need to check.

IPC is needed for X11 (or fallback X11)

**Comment by arteeh** [comment]
In that case I understand, closing.
