### ISSUE TITLE
Cannot install, app seemingly doesn't exist

### ISSUE THREAD

**Issue by mooreye** [flathub/org.gnome.Calculator#33]
```
$ flatpak -u install flathub org.gnome.Calculator
Looking for matches…
error: Nothing matches org.gnome.Calculator in remote flathub
```

What is going on? The app site https://flathub.org/apps/org.gnome.Calculator seems fine.

**Comment by A6GibKm** [comment]
I cannot reproduce, what flatpak version are you using?

**Comment by hfiguiere** [comment]
which architecture?

**Comment by mooreye** [comment]
Issue happens on Fedora 39, on Debian container it does not. So I'm closing this since it appears to be an issue with Fedora's verison of flatpak

**Comment by mooreye** [comment]
Narrowed down the issue to FLOSS subset.
Please see: https://github.com/flathub/org.gnome.Calculator/issues/34
